
package com.wondersgroup.smsCenter.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmsCenter", targetNamespace = "http://smscenter.sms.wondersgroup.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmsCenter {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.wondersgroup.smsCenter.client.SendSmsResp
     */
    @WebMethod(action = "urn:sendSms")
    @WebResult(name = "sendSmsResp", targetNamespace = "http://smscenter.sms.wondersgroup.com", partName = "parameter")
    public SendSmsResp sendSms(
        @WebParam(name = "sendSmsReq", targetNamespace = "http://smscenter.sms.wondersgroup.com", partName = "parameter")
        SendSmsReq parameter);

}
