
package com.wondersgroup.smsCenter.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmsCenterService", targetNamespace = "http://smscenter.sms.wondersgroup.com", wsdlLocation = "http://172.26.201.234:8081/SmsCenter/ws/SmsCenter?wsdl")
public class SmsCenterService
    extends Service
{

    private final static URL SMSCENTERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SMSCENTERSERVICE_EXCEPTION;
    private final static QName SMSCENTERSERVICE_QNAME = new QName("http://smscenter.sms.wondersgroup.com", "SmsCenterService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.26.201.234:8081/SmsCenter/ws/SmsCenter?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMSCENTERSERVICE_WSDL_LOCATION = url;
        SMSCENTERSERVICE_EXCEPTION = e;
    }

    public SmsCenterService() {
        super(__getWsdlLocation(), SMSCENTERSERVICE_QNAME);
    }

    public SmsCenterService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMSCENTERSERVICE_QNAME, features);
    }

    public SmsCenterService(URL wsdlLocation) {
        super(wsdlLocation, SMSCENTERSERVICE_QNAME);
    }

    public SmsCenterService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMSCENTERSERVICE_QNAME, features);
    }

    public SmsCenterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmsCenterService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmsCenter
     */
    @WebEndpoint(name = "SmsCenterServiceHttpSoapEndpoint")
    public SmsCenter getSmsCenterServiceHttpSoapEndpoint() {
        return super.getPort(new QName("http://smscenter.sms.wondersgroup.com", "SmsCenterServiceHttpSoapEndpoint"), SmsCenter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmsCenter
     */
    @WebEndpoint(name = "SmsCenterServiceHttpSoapEndpoint")
    public SmsCenter getSmsCenterServiceHttpSoapEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://smscenter.sms.wondersgroup.com", "SmsCenterServiceHttpSoapEndpoint"), SmsCenter.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMSCENTERSERVICE_EXCEPTION!= null) {
            throw SMSCENTERSERVICE_EXCEPTION;
        }
        return SMSCENTERSERVICE_WSDL_LOCATION;
    }

}
